spring:
    application:
        name: hashandra-node1

nodeConfigs:
    names:
        self: ${NODE_NAME1}
        node2: ${NODE_NAME2}
        node3: ${NODE_NAME3}
    urls:
        self: ${NODE_URL1}
        node2: ${NODE_URL2}
        node3: ${NODE_URL3}

server:
    port: ${SERVER_PORT}