spring:
    application:
        name: hashandra-node1

nodeConfig:
    names:
        node1: ${NODE_NAME1}
        node2: ${NODE_NAME2}
        node3: ${NODE_NAME3}
    urls:
        node1: ${NODE_URL1}
        node2: ${NODE_URL2}
        node3: ${NODE_URL3}